defaults:
  -
   scope:
     path: ""
     type: "posts"
   values:
     layout: "my-site3"
  -
   scope:
     path: "projects"
     type: "pages"
   values:
     layout: "project" # overrides previous default layout
     author: "Mr. Hyde"
